/* Copyright (c) 2026 Grayscale Luminary LLC. All rights reserved. */

/** Virtual module generated by scripts/library-sandbox-pdfjs.mjs: packed CMap name → base64 bytes. */
declare module 'graylum:pdf-cmaps' {
  const cmaps: Record<string, string>;
  export default cmaps;
}

declare module 'pdfjs-dist/legacy/build/pdf.worker.mjs' {
  export const WorkerMessageHandler: unknown;
}
