/* Copyright (c) 2026 Grayscale Luminary LLC. All rights reserved. */
import {fieldElicitation, type MethodInformationField} from '../../shared/opcMethodPolicy';
import {GROUNDED_CARD_CONTRACT} from '../runtime/groundedCard';
import {hostTurnContextSchema, type HostTurnContext} from '../runtime/hostTurn';
import {organizerAnswerCard, type AnsweredCard} from './answerCard';

export type CaptureState = {
  schema: readonly MethodInformationField[];
  values?: Record<string, {value?: unknown; status?: string; nature?: string}>;
  meta?: Record<string, {protected?: boolean}>;
  notes?: unknown[];
};
type Step = {id: string; title: string};
export function captureHostContext(steps: readonly Step[], information: Record<string, CaptureState>,
  stepId: string, opening: boolean): HostTurnContext {
  return hostTurnContextSchema.parse({cardContract: GROUNDED_CARD_CONTRACT, stepId, opening, checklist: steps.map(step => ({
    id: step.id, title: step.title,
    fields: (information[step.id]?.schema ?? []).map(field => {
      const state = information[step.id]!;
      const existing = state.values?.[field.id];
      const status = existing?.status === 'confirmed' || existing?.status === 'deferred'
        ? existing.status : typeof existing?.value === 'string' && existing.value.trim() ? 'draft' : 'missing';
      return {id: field.id, title: field.title ?? field.id, required: Boolean(field.required),
        role: fieldElicitation(field), status, protected: state.meta?.[field.id]?.protected ?? true};
    }),
  }))});
}
export function captureFocus(state: CaptureState): string {
  const missing = state.schema.find(field => field.required &&
    !(typeof state.values?.[field.id]?.value === 'string' && String(state.values[field.id]!.value).trim()));
  const field = missing ?? state.schema.find(field => state.values?.[field.id]?.status !== 'confirmed') ?? state.schema.at(-1);
  if (!field) throw new Error('OPC_QUESTION_NOT_REACHED');
  return field.id;
}
export function captureOrganizerInput(host: HostTurnContext, information: Record<string, CaptureState>,
  confirmed: Record<string, boolean>, userInput: string, answer?: AnsweredCard): string {
  const checklist = host.checklist.map(step => ({...step, confirmed: Boolean(confirmed[step.id]),
    fields: step.fields.map(field => ({...field, elicit: field.role,
      value: information[step.id]?.values?.[field.id]?.value ?? '',
      nature: information[step.id]?.values?.[field.id]?.nature ?? 'unknown',
    })),
    ...(!confirmed[step.id] ? {notes: information[step.id]?.notes ?? []} : {}),
  }));
  const serialize = () => JSON.stringify({captureFormat: 'v2', userInput, ...organizerAnswerCard(answer),
    originalStepId: host.stepId, checklist});
  let input = serialize();
  if (input.length > 24000) {
    for (const step of checklist) if (step.confirmed) for (const field of step.fields) field.value = '';
    input = serialize();
  }
  if (input.length > 24000) throw new Error('OPC_CAPTURE_INPUT_LIMIT');
  return input;
}

/** Projection generated by B1, after opc_step_material, is the only value/status authority. */
export function captureFrozenInformation(information: Record<string, CaptureState>,
  steps: Record<string, {information?: CaptureState['values']; fieldMeta?: CaptureState['meta']; notes?: unknown[]}>) {
  return Object.fromEntries(Object.entries(information).map(([id, state]) => {
    const frozen = steps[id];
    if (!frozen) throw new Error('OPC_CAPTURE_MATERIAL_MISMATCH');
    return [id, {schema: state.schema, values: frozen.information ?? {}, meta: frozen.fieldMeta ?? {}, notes: frozen.notes ?? []}];
  }));
}
